FROM python:latest

LABEL maintainer="irvan9110@gmail.com"


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV FLASK_DEBUG=1

COPY . ./usr/src/

WORKDIR /usr/src/

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 \
    && pip install celery

RUN pip install -r requirements.txt 

CMD ["flask","run","--debug"]


