

# creating a volume to be able to persist data between Postgres container restarts
volumes:
  postgres-db:


services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    stop_grace_period: 5s

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    image: ivan91110/web:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    env_file:
      - .env

  worker:
    build: 
      context: .    
      dockerfile: ./docker/dockerfile
    image: ivan91110/worker:latest
    command:  celery -A app:celery worker --loglevel INFO
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - postgres
      - redis