services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
