FROM python:latest

LABEL maintainer="irvan9110@gmail.com"


WORKDIR /usr/src/app


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV FLASK_DEBUG=1


RUN  apt-get update && apt-get install ca-certificates -y && update-ca-certificates \
    && apt-get install apt-transport-https \
    && echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" |  tee -a /etc/apt/sources.list.d/fury.list \
    &&  apt-get update \
    &&  apt-get install bearer 

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 \
    && pip install celery \
    && apt-get install bearer

# install python dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD ["gunicorn", "wsgi:app", "-b", "0.0.0.0:5000", "-w", "4"]


