"""empty message

Revision ID: 556db5724297
Revises: e65e34a2507f
Create Date: 2024-04-28 06:24:17.320151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556db5724297'
down_revision = 'e65e34a2507f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
