"""empty message

Revision ID: f1fd553ee95c
Revises: 
Create Date: 2024-04-20 02:59:33.075797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fd553ee95c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('fetch_status', sa.String(), nullable=False),
    sa.Column('analyze_status', sa.String(), nullable=False),
    sa.Column('analysis_request_at', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.Date(), nullable=True),
    sa.Column('analyze_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('git_repository',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('path_', sa.String(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_repository')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
